version: "3.8"
services:
  web:
    build: .
    command: >
      sh -c "python /code/manage.py migrate &&
             python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - MEDIAPP_BE_API_ENV=dev