# Generated by Django 3.2.3 on 2021-05-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='user_login',
            new_name='username',
        ),
    ]
