# Generated by Django 3.2.3 on 2021-05-21 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_remove_userlogin_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('group_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('is_limited', models.BooleanField(default=True)),
                ('members_limit', models.PositiveIntegerField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('membership_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.IntegerField()),
                ('status', models.IntegerField()),
                ('used_invitations', models.PositiveIntegerField(default=0)),
                ('remaining_invitations', models.PositiveIntegerField(default=5)),
                ('group', models.ForeignKey(blank=True, db_column='membership_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.group')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to='backoffice.userlogin')),
                ('user', models.ForeignKey(blank=True, db_column='membership_user', null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.userlogin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='backoffice.Membership', to='backoffice.UserLogin'),
        ),
    ]
