# Generated by Django 3.2.3 on 2021-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20210521_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
