# Generated by Django 3.2.3 on 2021-05-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20210521_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
