# Generated by Django 3.2.3 on 2021-05-25 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20210521_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('invitation_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.group')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_bye', to='backoffice.userlogin')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to='backoffice.userlogin')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
    ]
