# Generated by Django 3.2.3 on 2021-05-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='members_limit',
            field=models.IntegerField(default=5),
        ),
    ]
