# Generated by Django 3.2.3 on 2021-05-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_membership_members_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='members_limit',
        ),
        migrations.AlterField(
            model_name='group',
            name='members_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
